version: '3.7'
services:
  master:
    build: ./master
    ports:
      - "5000:5000"
    networks:
      - mapreduce-network
    command: "python master.py 5000"

  worker1:
    build: ./worker
    environment:
      MASTER_HOST: master
      PORT: "5000"
      WORKER_NAME: worker1
    command: "python worker.py master 5000 worker1"
    depends_on:
      - master
    networks:
      - mapreduce-network

  worker2:
    build: ./worker
    environment:
      MASTER_HOST: master
      PORT: "5000"
      WORKER_NAME: worker2
    command: "python worker.py master 5000 worker2"
    depends_on:
      - master
    networks:
      - mapreduce-network

networks:
  mapreduce-network:
    driver: bridge
