version: '3.7'
services:
  master:
    build:
      context: ./master
    ports:
      - "5000:5000"
    networks:
      - mapreduce-network

  worker1:
    build:
      context: ./worker
    environment:
      - MASTER_HOST=master
      - PORT=5000
      - WORKER_NAME=worker1
    command: python worker.py ${MASTER_HOST} ${PORT} ${WORKER_NAME}
    depends_on:
      - master
    networks:
      - mapreduce-network

  worker2:
    build:
      context: ./worker
    environment:
      - MASTER_HOST=master
      - PORT=5000
      - WORKER_NAME=worker2
    command: python worker.py ${MASTER_HOST} ${PORT} ${WORKER_NAME}
    depends_on:
      - master
    networks:
      - mapreduce-network

networks:
  mapreduce-network:
    driver: bridge
